#spring:
#  security:
#    oauth2:
#      authorizationserver:
#        client:
#          my-client:
#            require-authorization-consent: true
#            registration:
#              # mine / pass
#              client-id: myclient
#              client-secret: "{bcrypt}$2a$10$EbXaUVnjrkKoixjefxT5N.PQ2QRSStEv7ZJlP0zIOYu5T8rE0FulO"
#              authorization-grant-types: client_credentials, authorization_code, refresh_token
#              redirect-uris: http://127.0.0.1:8082/login/oauth2/code/spring
#              scopes: user.read,user.write,openid
#              client-authentication-methods: client_secret_basic
spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: 1111
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:oauth2-registered-client-schema.sql
        - classpath:user-schema.sql